# This file configures the analyzer to use the lint rule set from `package:flutter_lints`
include: package:flutter_lints/flutter.yaml

# The following line activates additional rules specifically for your project
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style rules
    - camel_case_types
    - library_names
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - implementation_imports
    - prefer_relative_imports
    - prefer_single_quotes
    - throw_in_finally
    
    # Flutter specific
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors